### ISSUE TITLE
AttributeError: 'MambaConfig' object has no attribute 'to_json_string'

### ISSUE THREAD

**Issue by bonolololo** [geronimi73/mamba#1]
Thanks for provinding code on how to finetune it but I get this error when I run it in google colab

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Map (num_proc=2): 100%
12947/12947 [00:16<00:00, 838.02 examples/s]
Map (num_proc=2): 100%
690/690 [00:01<00:00, 300.12 examples/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-37-de945876557f>](https://localhost:8080/#) in <cell line: 167>()
    165 )
    166 
--> 167 trainer.train()

4 frames
[/usr/local/lib/python3.10/dist-packages/transformers/integrations/integration_utils.py](https://localhost:8080/#) in on_train_begin(self, args, state, control, **kwargs)
    633                 model = kwargs["model"]
    634                 if hasattr(model, "config") and model.config is not None:
--> 635                     model_config_json = model.config.to_json_string()
    636                     self.tb_writer.add_text("model_config", model_config_json)
    637 

AttributeError: 'MambaConfig' object has no attribute 'to_json_string'

**Comment by geronimi73** [comment]
I guess the issue is the version of the transformers package, try 4.36.0
```pip install transformers==4.36.0```

**Comment by sovit-123** [comment]
It is happening when `Trainer` is trying to save model config to TensorBoard but `MambaConfig` does not have `to_json_string`.

In the `TrainingArguments` provide `report_to='none'` and it should run fine.

**Comment by geronimi73** [comment]
for ```report_to="wandb"``` works,  never used TensorBoard

**Comment by geronimi73** [comment]
did you make it work?

**Comment by sovit-123** [comment]
Actually, I have not tried using Tensorboard after that. I have just kept it disabled and it seems to work.
