### ISSUE TITLE
How to load fine tuned model model from a local model path?

### ISSUE THREAD

**Issue by javiermcebrian** [geronimi73/mamba#2]
Hi I checked your script for inference using a local model path:
https://github.com/geronimi73/mamba/blob/main/chat_mamba.py

Is this working? how did you made it work for a local path with a fine tuned model?

Thanks!

**Comment by javiermcebrian** [comment]
I think I obtained a solution. During training it is needed to save the config.json of the model config MambaConfig, I was not generating it with my training code.

**Comment by geronimi73** [comment]
this got a lot easier now with mamba integration into HF transformers, check this https://huggingface.co/collections/state-spaces/transformers-compatible-mamba-65e7b40ab87e5297e45ae406

but yes, `chat_mamba.py` should work too - still having trouble?

**Comment by javiermcebrian** [comment]
Thanks! Yes, I saw it is now in HF :)
Also, previously, I made it work serializing the config.json during training so that loading the model afterwards is possible.
Thanks!
